config/routes.rb
Rails.application.routes.draw do
  # get '/home'         , to: 'publics#home'         , as:  'home'           
  get '/published-articles'     , to: 'publics#articles'     , as:  'publics_articles'     
  get '/published-emissions'    , to: 'publics#emissions'    , as:  'publics_emissions'        
  get '/about'        , to: 'publics#about'        , as:  'about'      
  get '/contact'      , to: 'publics#contact'      , as:  'contact'      
  
  devise_for :users

Article.all.where(published: true).each do |article|
  get "/published-articles/#{article.slug}", controller: :publics, action: :show_article, id: article.id
end

Emission.all.where(published: true).each do |emission|
  get "/published-emissions/#{emission.title}", controller: :publics, action: :show_emission, id: emission.id
end


  resources :contents, path: "rtpx/admin/contents"
  resources :emissions, path: "rtpx/admin/emissions"
  resources :articles, path: "rtpx/admin/articles"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root 'pages#home'
  root 'publics#home'
  # root "posts#index"
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :emission
  belongs_to :user
  has_one_attached :media
  has_rich_text :description
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show; end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit; end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)
    @content.user_id = current_user.id

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy!

    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def content_params
    params.require(:content).permit(:title, :description, :media, :emission_id, :published, :user_id)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= content.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= content.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Media:</strong>
    <%= link_to content.media.filename, content.media if content.media.attached? %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Emission:</strong>
    <%= content.emission_id %>
  </p>

</div>

app/views/contents/_form.html.erb
<%= form_with(model: content, class: "contents") do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>
      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <div class="field">
      <%= form.label :description %>
      <%= form.rich_text_area :description , rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>
  <div class="my-5">
    <%= form.label :media %>
    <%= form.file_field :media, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :emission_id %>
    <%= form.collection_select :emission_id, Emission.all, :id, :title %>
  </div>
  <% if can? :create, Content %>
    <div class="my-5">
      <%= form.label :published %>
      <%= form.check_box :published, class: "block mt-2 h-5 w-5" %>
    </div>
  <% end %>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing content</h1>

  <%= render "form", content: @content %>

  <%= link_to "Show this content", @content, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to contents", contents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/contents/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% content_for :title, "Contents" %>
  <% if can? :create, Content %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Contents</h1>
      <%= link_to "New content", new_content_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  <% end %>
  <div id="contents" class="min-w-full">
    <% @contents.each do |content| %>
      <%= render content %>
      <p>
        <%= link_to "Show this content", content, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/contents/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New content</h1>

  <%= render "form", content: @content %>

  <%= link_to "Back to contents", contents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/contents/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @content %>
    <% if can? :update, @content %>
      <%= link_to "Edit this content", edit_content_path(@content), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
    <%= link_to "Back to contents", contents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if can? :destroy, @content %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this content", @content, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <% end %>
  </div>
</div>