config/routes.rb
Rails.application.routes.draw do
  # get '/home'         , to: 'publics#home'         , as:  'home'           
  get '/published-articles'     , to: 'publics#articles'     , as:  'publics_articles'     
  get '/published-emissions'    , to: 'publics#emissions'    , as:  'publics_emissions'        
  get '/about'        , to: 'publics#about'        , as:  'about'      
  get '/contact'      , to: 'publics#contact'      , as:  'contact'      
  
  devise_for :users

Article.all.where(published: true).each do |article|
  get "/published-articles/#{article.slug}", controller: :publics, action: :show_article, id: article.id
end

Emission.all.where(published: true).each do |emission|
  get "/published-emissions/#{emission.title}", controller: :publics, action: :show_emission, id: emission.id
end


  resources :contents, path: "rtpx/admin/contents"
  resources :emissions, path: "rtpx/admin/emissions"
  resources :articles, path: "rtpx/admin/articles"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root 'pages#home'
  root 'publics#home'
  # root "posts#index"
end

app/views/shared/_devise.flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_devise_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navigation.html.erb
<nav>
  <ul class="flex justify-center space-x-3">
    <li>
      <%= link_to root_path do %>
        Acceuil
      <%end%>
    </li>
    <li>
      <%= link_to emissions_path do %>
        Emissions
      <%end%>
    </li>
    <li>
      <%= link_to articles_path do %>
        Articles
      <%end%>
    </li>
    <li>
      <%= link_to contents_path do %>
        Contents
      <%end%>
    </li>
    <% if current_user %>
      <li>
        Hello <%= current_user.email %>
      </li>
      <li>
        You are Role: <%= current_user.role %>
      </li>
      <% if current_user.admin? %>
        <li>
          User Total count <%= User.count %>
        </li>
      <% end %>
      <li>
        <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "are you sure" }%>
      </li>
    <%end%>
  </ul>
</nav>

app/views/shared/_public_employe_card.html.erb
<div class="w-full max-w-sm bg-gradient-to-r from-emerald-200 to-emerald-900 border border-gray-200 rounded-lg shadow ">
  <div class="flex justify-end px-4 pt-4">
    <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
      <span class="sr-only">Open dropdown</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
        <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
      </svg>
    </button>
    <!-- Dropdown menu -->
    <div id="dropdown" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
      <ul class="py-2" aria-labelledby="dropdownButton">
        <li>
          <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Facebook</a>
        </li>
        <li>
          <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Twitter</a>
        </li>
        <li>
          <a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Telegram</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="flex flex-col items-center pb-10">
    <%= image_tag image, class: "w-24 h-24 mb-3 rounded-full shadow-lg", alt: "dummy ..." %>
    <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">Bonnie Jean</h5>
    <span class="text-sm text-gray-500 dark:text-gray-400">Journalis</span>
    <div class="flex mt-4 md:mt-6">
      <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add friend</a>
      <a href="#" class="py-2 px-4 ms-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Message</a>
    </div>
  </div>
</div>

app/views/shared/_public_navigation.html.erb
<nav class="border-gray-200 bg-white shadow p-4 mb-10 sticky top-0 ">
  <div class="container mx-auto flex flex-wrap items-center justify-between">
    <%= link_to root_path, class: "flex" do %>
      <%= image_tag 'logo.jpg', class: "h-10 mr-3 splash_border", size: "51x71", alt: "logo"  %>
      <span class="self-center text-lg font-semibold whitespace-nowrap">Radio&nbsp;Tele</span>
    <%end%>
    <div class="flex md:order-2">
      <div class="relative mr-3 md:mr-0 hidden md:block">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
        </div>
        <input type="text" id="email-adress-icon" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2" placeholder="Search...">
      </div>
      <button data-collapse-toggle=" mobile_menu" type="button" class="md:hidden text-gray-400 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-300 rounded-lg inline-flex items-center justify-center" aria-controls=" mobile_menu" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </button>
    </div>
    <div class="hidden md:flex justify-between items-center w-full md:w-auto md:order-1" id=" mobile_menu">
      <ul class="flex-col md:flex-row flex md:space-x-8 mt-4 md:mt-0 md:text-sm md:font-medium">
        <li>
          <%= link_to root_path ,class: "bg-blue-700 md:bg-transparent text-white block pl-3 pr-4 py-2 md:text-blue-700 md:p-0 rounded", aria:{current: "page"} do %>Home <%end%>
        </li>
        <li>
          <%= link_to about_path ,class: "text-gray-700 hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 block pl-3 pr-4 py-2 md:hover:text-blue-700 md:p-0" do %>About <%end%>
        </li>
        <li>
          <%= link_to publics_emissions_path ,class: "text-gray-700 hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 block pl-3 pr-4 py-2 md:hover:text-blue-700 md:p-0" do %>Emissions <%end%>
        </li>
        <li>
          <%= link_to publics_articles_path ,class: "text-gray-700 hover:bg-gray-50 border-b border-gray-100 md:hover:bg-transparent md:border-0 block pl-3 pr-4 py-2 md:hover:text-blue-700 md:p-0" do %>Articles <%end%>
        </li>
        <li>
          <%= link_to contact_path ,class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium cursor-pointer" do %>Contact <%end%>
        </li>
      </ul>
    </div>
  </div>
</nav>