config/routes.rb
Rails.application.routes.draw do
  # get '/home'         , to: 'publics#home'         , as:  'home'           
  get '/published-articles'     , to: 'publics#articles'     , as:  'publics_articles'     
  get '/published-emissions'    , to: 'publics#emissions'    , as:  'publics_emissions'        
  get '/about'        , to: 'publics#about'        , as:  'about'      
  get '/contact'      , to: 'publics#contact'      , as:  'contact'      
  
  devise_for :users

Article.all.where(published: true).each do |article|
  get "/published-articles/#{article.slug}", controller: :publics, action: :show_article, id: article.id
end

Emission.all.where(published: true).each do |emission|
  get "/published-emissions/#{emission.title}", controller: :publics, action: :show_emission, id: emission.id
end


  resources :contents, path: "rtpx/admin/contents"
  resources :emissions, path: "rtpx/admin/emissions"
  resources :articles, path: "rtpx/admin/articles"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root 'pages#home'
  root 'publics#home'
  # root "posts#index"
end

app/models/emission.rb
class Emission < ApplicationRecord
  has_many :contents
  has_one_attached :poster
  has_rich_text :description
end

app/controllers/emissions_controller.rb
class EmissionsController < ApplicationController
  before_action :set_emission, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /emissions or /emissions.json
  def index
    @emissions = Emission.all
  end

  # GET /emissions/1 or /emissions/1.json
  def show; end

  # GET /emissions/new
  def new
    @emission = Emission.new
  end

  # GET /emissions/1/edit
  def edit; end

  # POST /emissions or /emissions.json
  def create
    @emission = Emission.new(emission_params)
    @emission.user_id = current_user.id

    respond_to do |format|
      if @emission.save
        format.html { redirect_to emission_url(@emission), notice: 'Emission was successfully created.' }
        format.json { render :show, status: :created, location: @emission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emissions/1 or /emissions/1.json
  def update
    respond_to do |format|
      if @emission.update(emission_params)
        format.html { redirect_to emission_url(@emission), notice: 'Emission was successfully updated.' }
        format.json { render :show, status: :ok, location: @emission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emissions/1 or /emissions/1.json
  def destroy
    @emission.destroy!

    respond_to do |format|
      format.html { redirect_to emissions_url, notice: 'Emission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_emission
    @emission = Emission.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def emission_params
    params.require(:emission).permit(:title, :presenter, :description, :poster, :published, :user_id)
  end
end

app/helpers/emissions_helper.rb
module EmissionsHelper
end

app/views/emissions/_emission.html.erb
<div id="<%= dom_id emission %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= emission.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Presenter:</strong>
    <%= emission.presenter %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= emission.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Poster:</strong>
    <%= link_to emission.poster.filename, emission.poster if emission.poster.attached? %>
  </p>

</div>

app/views/emissions/_form.html.erb
<%= form_with(model: emission, class: "contents") do |form| %>
  <% if emission.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(emission.errors.count, "error") %> prohibited this emission from being saved:</h2>
      <ul>
        <% emission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :presenter %>
    <%= form.text_field :presenter, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <div class="field">
      <%= form.label :description %>
      <%= form.rich_text_area :description , rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>
  <div class="my-5">
    <%= form.label :poster %>
    <%= form.file_field :poster, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <% if can? :create, Emission %>
    <div class="my-5">
      <%= form.label :published %>
      <%= form.check_box :published, class: "block mt-2 h-5 w-5" %>
    </div>
  <% end %>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/emissions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing emission</h1>

  <%= render "form", emission: @emission %>

  <%= link_to "Show this emission", @emission, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to emissions", emissions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/emissions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% content_for :title, "Emissions" %>
  <% if can? :create, Emission %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Emissions</h1>
      <%= link_to "New emission", new_emission_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  <% end %>
  <div id="emissions" class="min-w-full">
    <% @emissions.each do |emission| %>
      <%= render emission %>
      <p>
        <%= link_to "Show this emission", emission, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/emissions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New emission</h1>

  <%= render "form", emission: @emission %>

  <%= link_to "Back to emissions", emissions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/emissions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @emission %>
    <% if can? :update, @emission %>
      <%= link_to "Edit this emission", edit_emission_path(@emission), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
    <%= link_to "Back to emissions", emissions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if can? :destroy, @emission %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this emission", @emission, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <% end %>
  </div>
</div>